<?php

namespace App\Core\Console\Commands;

use App\Core\ModuleManager;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class CacheModuleProvidersCommand extends Command
{
    /**
     * The name and signature of the console command.
     */
    protected $signature = 'module:cache
                            {--clear : Clear the module cache instead of generating it}';

    /**
     * The console command description.
     */
    protected $description = 'Cache the discovered module providers for production';

    /**
     * Execute the console command.
     */
    public function handle(ModuleManager $moduleManager): int
    {
        if ($this->option('clear')) {
            return $this->clearCache();
        }

        $this->info('Discovering modules and their providers...');

        // Discover all modules
        $moduleManager->discoverModules();
        $providersByModule = $moduleManager->getServiceProvidersByModule();

        if (empty($providersByModule)) {
            $this->error('No module providers found to cache.');
            return 1;
        }

        // Generate manifest content
        $manifestContent = $this->generateManifestContent($providersByModule);

        // Write to cache file
        $cachePath = base_path('bootstrap/cache/modules.php');
        File::put($cachePath, $manifestContent);

        // Display summary
        $this->displaySummary($providersByModule);

        $this->info('');
        $this->info("Module providers cached successfully to: {$cachePath}");
        $this->info('');
        $this->comment('💡 Remember to run this command after:');
        $this->comment('   - Adding new modules');
        $this->comment('   - Adding new service providers to existing modules');
        $this->comment('   - Deploying to production');

        return 0;
    }

    /**
     * Clear the module cache
     */
    protected function clearCache(): int
    {
        $cachePath = base_path('bootstrap/cache/modules.php');

        if (File::exists($cachePath)) {
            File::delete($cachePath);
            $this->info('Module provider cache cleared successfully.');
        } else {
            $this->info('No module cache found to clear.');
        }

        return 0;
    }

    /**
     * Generate the manifest file content
     */
    protected function generateManifestContent(array $providersByModule): string
    {
        $export = var_export($providersByModule, true);

        return <<<PHP
<?php

/**
 * Module Providers Manifest
 *
 * This file is automatically generated by the module:cache command.
 * Do not edit this file manually.
 *
 * Generated: {$this->getCurrentTimestamp()}
 */

return {$export};

PHP;
    }

    /**
     * Display cache summary
     */
    protected function displaySummary(array $providersByModule): void
    {
        $this->info('');
        $this->info('Module Providers Cache Summary');
        $this->info('═══════════════════════════════════════════════');

        $totalProviders = 0;

        foreach ($providersByModule as $moduleName => $providers) {
            $count = count($providers);
            $totalProviders += $count;

            $this->line("  <comment>{$moduleName}</comment>: {$count} provider(s)");

            foreach ($providers as $provider) {
                $shortName = class_basename($provider);
                $this->line("    ├─ {$shortName}");
            }
        }

        $this->info('═══════════════════════════════════════════════');
        $this->info("Total Modules: " . count($providersByModule));
        $this->info("Total Providers: {$totalProviders}");
    }

    /**
     * Get current timestamp
     */
    protected function getCurrentTimestamp(): string
    {
        return now()->format('Y-m-d H:i:s');
    }
}

